<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Android" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Browser" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.0.5" />
    <PackageVersion Include="Avalonia.iOS" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageVersion Include="CoreCLR-NCalc" Version="3.1.253" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Dock.Avalonia" Version="12.0.0.2" />
    <PackageVersion Include="Dock.Avalonia.Themes.Fluent" Version="12.0.0.2" />
    <PackageVersion Include="Dock.Model" Version="12.0.0.2" />
    <PackageVersion Include="Dock.Model.Avalonia" Version="12.0.0.2" />
    <PackageVersion Include="Dock.Model.Mvvm" Version="12.0.0.2" />
    <PackageVersion Include="Dock.Settings" Version="12.0.0.2" />
    <PackageVersion Include="DynamicLocalization.Avalonia" Version="2.1.0" />
    <PackageVersion Include="DynamicLocalization.Core" Version="2.1.0" />
    <PackageVersion Include="Irihi.Ursa" Version="2.1.0" />
    <PackageVersion Include="Irihi.Ursa.Themes.Semi" Version="2.1.0" />
    <PackageVersion Include="LibVLCSharp" Version="3.10.0" />
    <PackageVersion Include="LibVLCSharp.Avalonia" Version="3.10.0" />
    <PackageVersion Include="Markdown.Avalonia" Version="12.0.0-a3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.1.25080.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-preview.1.25080.5" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageVersion Include="Semi.Avalonia.ColorPicker" Version="12.0.3" />
    <PackageVersion Include="Semi.Avalonia.Dock" Version="12.0.0.2" />
    <PackageVersion Include="Serilog" Version="4.2.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.15" />
  </ItemGroup>
</Project>
