<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="Serilog" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GalNet.Core\GalNet.Core.csproj" />
        <ProjectReference Include="..\GalNet.Assets\GalNet.Assets.csproj" />
        <ProjectReference Include="..\GalNet.Editor.Abstraction\GalNet.Editor.Abstraction.csproj" />
        <ProjectReference Include="..\GalNet.Runtime\GalNet.Runtime.csproj" />
        <ProjectReference Include="..\GalNet.Storage.Abstractions\GalNet.Storage.Abstractions.csproj" />
    </ItemGroup>

</Project>
