<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\GalNet.Core\GalNet.Core.csproj" />
      <ProjectReference Include="..\GalNet.Presentation.Abstractions\GalNet.Presentation.Abstractions.csproj" />
      <ProjectReference Include="..\GalNet.Storage.Abstractions\GalNet.Storage.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CoreCLR-NCalc" />
      <PackageReference Include="Serilog" />
    </ItemGroup>

</Project>
