namespace GalNet.Core.Variable;

/// <summary>A host-provided variable declaration that is generated by a built-in subsystem.</summary>
public sealed class SystemVariableDefinition
{
    public required string Owner { get; init; }
    public required string Name { get; init; }
    public required VariableScope Scope { get; init; }
    public required Variable DefaultValue { get; init; }
}
