<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" />
      <PackageReference Include="CommunityToolkit.Mvvm" />
      <PackageReference Include="DynamicLocalization.Avalonia" />
      <PackageReference Include="Irihi.Ursa" />
      <PackageReference Include="Irihi.Ursa.Themes.Semi" />
      <PackageReference Include="LibVLCSharp" />
      <PackageReference Include="LibVLCSharp.Avalonia" />
      <PackageReference Include="Markdown.Avalonia" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="VideoLAN.LibVLC.Windows" />
      <PackageReference Include="Serilog" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GalNet.Control.Abstraction\GalNet.Control.Abstraction.csproj" />
      <ProjectReference Include="..\GalNet.Core\GalNet.Core.csproj" />
      <ProjectReference Include="..\GalNet.Presentation.Abstractions\GalNet.Presentation.Abstractions.csproj" />
      <ProjectReference Include="..\GalNet.Presentation.Defaults\GalNet.Presentation.Defaults.csproj" />
      <ProjectReference Include="..\GalNet.Runtime\GalNet.Runtime.csproj" />
      <ProjectReference Include="..\GalNet.Storage.Abstractions\GalNet.Storage.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Screen\Host\GameHostView.axaml.cs">
        <DependentUpon>GameHostView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Screen\SaveLoad\SaveSlotCard.axaml.cs">
        <DependentUpon>SaveSlotCard.axaml</DependentUpon>
      </Compile>
      <Compile Update="Screen\Title\TextMenuTitleView.axaml.cs">
        <DependentUpon>TextMenuTitleView.axaml</DependentUpon>
      </Compile>
      <Compile Update="Controls\AssetPicker.axaml.cs">
        <DependentUpon>AssetPicker.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
